////////////////////////////////////////////////////////
/***                             [Peach Core]                                ***/
////////////////////////////////////////////////////////
/***                            [Version 0.0.01]                             ***/
////////////////////////////////////////////////////////
/***  Copyright(c) 2024-present Ranyodh Singh Mandur  ***/
/***                               MIT License                                ***/
/***         Documentation: TBD                                          ***/
/*** GitHub: https://github.com/iLoveJohnFish/Peach-E ***/
/////////////////////////////////////////////////////////
#pragma once

///PeachCore
#include "ResourceManager.h"

//////// Rendering Backends ////////

#ifdef PEACH_RENDERER_OPENGL
#include "../Rendering/OpenGL/Desktop/OpenGLRenderer.h"
#endif

#ifdef PEACH_RENDERER_VULKAN
#include "../Rendering/Vulkan/VulkanRenderer.h"
#endif

#ifdef PEACH_RENDERER_METAL 
#include "../Rendering/Metal/MetalRenderer.h"
#endif

#ifdef PEACH_RENDERER_OPENGL_ES
#include "../Rendering/OpenGL/Mobile/MobileGLRenderer.h"
#endif

#ifdef PEACH_RENDERER_WEBGL
#include "../Rendering/OpenGL/Browser/WebGLRenderer.h"
#endif

//////// Rendering Primitives ////////

#include "../Rendering/PeachMaterial.h"
#include "../Rendering/PeachTexture.h"

//////// Input ////////

#include "InputManager.h"

#include "../Scene-Items/PeachNode.h"
#include "../Scene-Items/SceneTree.h"

#include "../Scene-Items/UI/PeachConsole.h"

namespace PeachCore {

    //////////////////////////////////////////////
    // Rendering backend helper Enum
    //////////////////////////////////////////////

    enum class RendererType : int
    {
        OpenGL,
        Vulkan,
        Metal
    };

    //////////////////////////////////////////////
    // Rendering word size
    //////////////////////////////////////////////

    struct RenderCommand 
    {
        uint32_t node_id;       // 4 bytes
        uint16_t opcode;        // 2 bytes
        uint16_t reserved;      // 2 bytes (alignment or flags)
        uint64_t operand;       // 8 bytes
    };

    //////////////////////////////////////////////
    // Rendering OPCODES
    //////////////////////////////////////////////

/*                            | Name                 | ID |   Operand                | 
                               | ---------------- - | ---- | ---------------------- | 
*/

    //constexpr enum RENDER_OP : uint8_t
    //{
    //    constexpr uint8_t RENDER_NOP = 0x00;
    //    constexpr uint8_t RENDER_CREATE_NODE_OP = 0x01;//| pointer to shape def |
    //    constexpr uint8_t RENDER_DESTROY_NODE_OP = 0x02; // | � |
    //    constexpr uint8_t RENDER_UPDATE_POSITION_OP = 0x03; // | packed vec2 |
    //    constexpr uint8_t RENDER_UPDATE_SCALE_OP = 0x04;// | packed vec2 |
    //    constexpr uint8_t RENDER_SET_COLOR_OP = 0x05;// | 32 - bit RGBA |
    //    constexpr uint8_t RENDER_DONT_DRAW_OP = 0x06;// | � |
    //    constexpr uint8_t RENDER_SET_TEXTURE_OP = 0x07;// | texture handle |
    //    constexpr uint8_t RENDER_LERP_POSITION_OP = 0x08;// | pointer to lerp config |
    //    constexpr uint8_t RENDER_SET_TRANSFORM_OP = 0x09;// | pointer to mat4 |
    //    constexpr uint8_t RENDER_PUSH_STATE_OP = 0x0A;// | � |
    //    constexpr uint8_t RENDER_POP_STATE_OP = 0x0B;// | � |

    //    constexpr uint8_t RENDER_OP_FRAME_END = 0x0C; // | Used for render thread to figure out when to sleep

    //    constexpr uint8_t RENDER_SHUTDOWN_THREAD = 0x0D; //used for shutting down render thread appropriately uwu
    //};
        
    using RenderCommandPipe = moodycamel::ReaderWriterQueue<RenderCommand, MOODY_CAMEL_QUEUE_SIZE>;

    using FontID = uint32_t; //Font handle used to link a PUI element -> a specific font family generated by msdfgen for the renderer uwu

    struct Font //PUI nodes just use a string buffer and then link via a FontID for rendering to screen uwu
    {

    };

    //////////////////////////////////////////////
    // Rendering Manager Class
    //////////////////////////////////////////////
    class RenderingManager 
    {
    //////////////////////////////////////////////
    // Private Destructor
    //////////////////////////////////////////////
    private:
        //IMPORTANT: not really needed to cleanup here and the OS will def clear the memory block associated w the process quicker, RenderingManager Lifetime = Process Lifetime
        ~RenderingManager() = default; 

    //////////////////////////////////////////////
    // Singleton Instance
    //////////////////////////////////////////////
    public:
        static RenderingManager& get_single() 
        {
            static RenderingManager rendering_manager;
            return rendering_manager;
        }
    //////////////////////////////////////////////
    // Private Constructor
    //////////////////////////////////////////////
    private:
        explicit RenderingManager() = default; //explicitly nothing UwU >O<
        RenderingManager(const RenderingManager&) = delete;
        RenderingManager& operator=(const RenderingManager&) = delete;

        RenderingManager(RenderingManager&&) = delete;
        RenderingManager& operator=(RenderingManager&&) = delete;

    //////////////////////////////////////////////
    // Private Members
    //////////////////////////////////////////////
    private:
#ifdef PEACH_RENDERER_METAL 
        unique_ptr<Metal::Renderer> pm_MetalRenderer = nullptr;
#endif
#ifdef PEACH_RENDERER_VULKAN
        unique_ptr<Vulkan::Renderer> pm_VulkanRenderer = nullptr;
#endif
#ifdef PEACH_RENDERER_OPENGL
        unique_ptr<OpenGL::Renderer> pm_OpenGLRenderer = nullptr; //OpenGL not supported on mac anymore fuck you tim apple
#endif
#ifdef PEACH_RENDERER_OPENGL_ES
#endif
#ifdef PEACH_RENDERER_WEBGL
#endif

        size_t pm_CurrentFrameRateLimit = 0u;
        size_t pm_CurrentFrame = 0u;

        float RENDER_FRAME_TIME_STEP = 1000.0f;

        bool pm_IsVSyncEnabled = false;

        // list of all Node ID's, SceneTree translates from string ID -> uint64_t ID 
        vector<uint64_t> pm_RenderableNodes; //NOTE: doesn't need to be multi thread friendly so the reallocs don't really matter

        //////////////////// Command/Resource Queue ////////////////////

        shared_ptr<RenderCommandPipe> pm_RenderCommandQueue = nullptr;
        shared_ptr<ResourcePipe> pm_LoadedResourceQueue = nullptr;

        //////////////////// Window Stuff ////////////////////

        SDL_Window* pm_MainWindow = nullptr;
        unordered_map<SDL_WindowID, SDL_Window*> pm_CurrentlyActiveWindows;
        vector<SDL_WindowID> pm_CloseWindowRequests;

        //////////////////// Logger ////////////////////

        shared_ptr<Logger> rendering_logger = nullptr;

        unique_ptr<unsigned char> pm_DefaultTexture = nullptr;

    public: 
        atomic<bool> pm_IsRunning{ true }; //this doesn't need to be atomic but whatevs, or even needed tbh but probs helpful for the while loop maybes
        atomic<bool> pm_IsInitialized{ false };

    //////////////////////////////////////////////
    // Public Methods
    //////////////////////////////////////////////
    public:

#ifdef PEACH_RENDERER_VULKAN
        void
            RenderLoopVK
            (
                const string& fp_LogOutputDirectory,
                latch& fp_InitLatch,
                SDL_Window* fp_MainWindow,
                const size_t fp_InitialFrameRate
            );

    private:
        [[nodiscard]] bool
            InitializeVulkan();

        [[nodiscard]] bool
            PresentFrameVK();
    public:
#endif

#ifdef PEACH_RENDERER_OPENGL
        void
            RenderLoopGL
            (
                const string& fp_LogOutputDirectory,
                latch& fp_InitLatch,
                SDL_Window* fp_MainWindow,
                const size_t fp_InitialFrameRate
            );

        bool
            CreateOpenGLRenderer
            (
                SDL_Window* fp_Window
            );

        void
            DestroyOpenGLRenderer();

        [[nodiscard]] OpenGL::Renderer*const
            GetOpenGLRenderer();

    private:
        //wip? future me: WORKING BITCH
        [[nodiscard]] PEACH_STATUS_CODE
            InitializeOpenGL();

        [[nodiscard]] bool
            PresentFrameGL();
    public:

#endif

#ifdef PEACH_RENDERER_METAL 
        void
            RenderLoopMetal
            (
                const string& fp_LogOutputDirectory,
                latch& fp_InitLatch,
                SDL_Window* fp_MainWindow,
                const size_t fp_InitialFrameRate
            );

        [[nodiscard]] PEACH_STATUS_CODE
            InitializeMetal();

        [[nodiscard]] bool
            PresentFrameMetal();
#endif

        void
            Stop()
            noexcept;

        [[nodiscard]] shared_ptr<RenderCommandPipe>
            GetDrawCommandQueue
            (
                Logger*const logger
            ); //this is supposed to be called from the main thread so cant use the rendering_logger here for thread reasons

        void 
            ResizeWindow();

        void 
            GetCurrentViewPort();

        [[nodiscard]] bool
            IsActive()
            const noexcept
        {
            return pm_IsRunning.load(std::memory_order_acquire);
        }

        [[nodiscard]] size_t
            GetCurrentFrameRateLimit()
            const noexcept;

        void
            SetNewFrameRateLimit(const size_t fp_NewFrameRateLimit)
            noexcept;

        [[nodiscard]] bool 
            IsVSyncEnabled() 
            const noexcept;

        [[nodiscard]] SDL_Window*
            GetMainWindow()
            const noexcept
        {
            return pm_MainWindow;
        }

        void
            SetVSync(const bool fp_IsEnabled)
            noexcept;

    //////////////////////////////////////////////
    // Private Methods
    //////////////////////////////////////////////
    private:
        /*
            These LERP functions are used for interpolating sprite positions between physics update frames if the rendering fps is > 60 since physics
            will always update at a constant update interval of 60 times a second, equally spaced apart. This way you'll get "smoother" graphics if u wanna
            crank up the fps uwu



            The idea is that the most recent position will be used, and if the last used position idfk idk if thisll work since i cant predict the next frame, and if i use the current frame data and last frames, then the visuals will be outta sync
            with the current real position which is no good for gameplay, and tryna do predictions like that could be a bad route if the render time oversteps its processing tiime.
        */
        inline const float
            Lerp(const float fp_Start, const float fp_End, const float fp_Rate)
            const noexcept
        {
            return fp_Start * (1 - fp_Rate) + fp_End * fp_Rate;

        }

        inline const glm::vec2
            Lerp(const glm::vec2& fp_Start, const glm::vec2& fp_End, const glm::vec2& fp_Rate)
            const noexcept
        {
            return glm::vec2(0);
        }

        [[nodiscard]] bool
            Initialize
            (
                const string& fp_LogOutputDirectory,
                const size_t fp_InitialFrameRate
            );

        bool
            InitializeLoadingQueue();

        bool
            InitializeDrawCommandQueue();

        [[nodiscard]] bool
            ProcessCommands();

        void
            Shutdown();
    };
}
