////////////////////////////////////////////////////////
/***                             [Peach Core]                                ***/
////////////////////////////////////////////////////////
/***                            [Version 0.0.01]                             ***/
////////////////////////////////////////////////////////
/***  Copyright(c) 2024-present Ranyodh Singh Mandur  ***/
/***                               MIT License                                ***/
/***         Documentation: TBD                                          ***/
/*** GitHub: https://github.com/iLoveJohnFish/Peach-E ***/
/////////////////////////////////////////////////////////
#pragma once

///PeachCore
#include "ResourceManager.h"
#include "peach_api/StatusCodes.h"

//////// Rendering Backends ////////

#ifdef PEACH_RENDERER_OPENGL
#   include "rendering/OpenGL/Desktop/OpenGLRenderer.h"
#endif

#ifdef PEACH_RENDERER_VULKAN
#   include "rendering/Vulkan/VulkanRenderer.h"
#endif

#ifdef PEACH_RENDERER_METAL 
#   include "../rendering/Metal/MetalRenderer.h"
#endif

#ifdef PEACH_RENDERER_OPENGL_ES
#   include "../rendering/OpenGL/Mobile/MobileGLRenderer.h"
#endif

#ifdef PEACH_RENDERER_WEBGL
#   include <SDL3/SDL.h>
#   include "../rendering/OpenGL/Browser/WebGLRenderer.h"
#endif

//////// Rendering Primitives ////////



//////// Input ////////


namespace PeachCore {

    //////////////////////////////////////////////
    // Rendering backend helper Enum
    //////////////////////////////////////////////

    enum class RendererType : int
    {
        OpenGL,
        WebGL,
        MobileGL,
        Vulkan,
        Metal
    };

    //////////////////////////////////////////////
    // Rendering word size
    //////////////////////////////////////////////

    struct RenderCommand 
    {
        uint32_t node_id;       // 4 bytes
        uint16_t opcode;        // 2 bytes
        uint16_t reserved;      // 2 bytes (alignment or flags)
        uint64_t operand;       // 8 bytes
    };

    //////////////////////////////////////////////
    // Rendering OPCODES
    //////////////////////////////////////////////

/*                            | Name                 | ID |   Operand                | 
                               | ---------------- - | ---- | ---------------------- | 
*/

    //constexpr enum RENDER_OP : uint8_t
    //{
    //    constexpr uint8_t RENDER_NOP = 0x00;
    //    constexpr uint8_t RENDER_CREATE_NODE_OP = 0x01;//| pointer to shape def |
    //    constexpr uint8_t RENDER_DESTROY_NODE_OP = 0x02; // | � |
    //    constexpr uint8_t RENDER_UPDATE_POSITION_OP = 0x03; // | packed vec2 |
    //    constexpr uint8_t RENDER_UPDATE_SCALE_OP = 0x04;// | packed vec2 |
    //    constexpr uint8_t RENDER_SET_COLOR_OP = 0x05;// | 32 - bit RGBA |
    //    constexpr uint8_t RENDER_DONT_DRAW_OP = 0x06;// | � |
    //    constexpr uint8_t RENDER_SET_TEXTURE_OP = 0x07;// | texture handle |
    //    constexpr uint8_t RENDER_LERP_POSITION_OP = 0x08;// | pointer to lerp config |
    //    constexpr uint8_t RENDER_SET_TRANSFORM_OP = 0x09;// | pointer to mat4 |
    //    constexpr uint8_t RENDER_PUSH_STATE_OP = 0x0A;// | � |
    //    constexpr uint8_t RENDER_POP_STATE_OP = 0x0B;// | � |

    constexpr uint8_t RENDER_CREATE_TEXTURE = 0x01;

    //    constexpr uint8_t RENDER_OP_FRAME_END = 0x0C; // | Used for render thread to figure out when to sleep

    //    constexpr uint8_t RENDER_SHUTDOWN_THREAD = 0x0D; //used for shutting down render thread appropriately uwu
    //};
        
    using RenderCommandPipe = moodycamel::ReaderWriterQueue<RenderCommand, MOODY_CAMEL_QUEUE_SIZE>;

    using FontID = uint32_t; //Font handle used to link a PUI element -> a specific font family generated by msdfgen for the renderer uwu

    struct Font //PUI nodes just use a string buffer and then link via a FontID for rendering to screen uwu
    {

    };

    struct GameManager;

    //////////////////////////////////////////////
    // Rendering Manager Class
    //////////////////////////////////////////////
    class RenderingManager 
    {
    //////////////////////////////////////////////
    // Public Destructor
    //////////////////////////////////////////////
    public:
        //IMPORTANT: not really needed to cleanup here and the OS will def clear the memory block associated w the process quicker, RenderingManager Lifetime = Process Lifetime
        ~RenderingManager() = default; 

    //////////////////////////////////////////////
    // Private Constructor
    //////////////////////////////////////////////
    private:
        friend GameManager;

        explicit RenderingManager() = default; //explicitly nothing UwU >O<
        RenderingManager(const RenderingManager&) = delete;
        RenderingManager& operator=(const RenderingManager&) = delete;

        RenderingManager(RenderingManager&&) = delete;
        RenderingManager& operator=(RenderingManager&&) = delete;

    //////////////////////////////////////////////
    // Private Members
    //////////////////////////////////////////////
    private:

        thread pm_RenderThread;

        #ifdef PEACH_RENDERER_METAL 
            unique_ptr<Metal::Renderer> pm_MetalRenderer = nullptr;
        #endif
        #ifdef PEACH_RENDERER_VULKAN
            unique_ptr<Vulkan::Renderer> pm_VulkanRenderer = nullptr;
        #endif
        #ifdef PEACH_RENDERER_OPENGL
            unique_ptr<OpenGL::Renderer> pm_OpenGLRenderer = nullptr; //OpenGL not supported on mac anymore fuck you tim apple
        #endif
        #ifdef PEACH_RENDERER_OPENGL_ES
            unique_ptr<MobileGL::Renderer> pm_WebGLRenderer = nullptr;
        #endif
        #ifdef PEACH_RENDERER_WEBGL
            unique_ptr<WebGL::Renderer> pm_MobileGLRenderer = nullptr;
        #endif

        size_t pm_CurrentFrameRateLimit = 0u;
        size_t pm_CurrentFrame = 0u;

        float RENDER_FRAME_TIME_STEP = 1000.0f;

        bool pm_IsVSyncEnabled = false;

        // list of all Node ID's, SceneTree translates from string ID -> uint64_t ID 
        vector<uint64_t> pm_RenderableNodes; //NOTE: doesn't need to be multi thread friendly so the reallocs don't really matter

        //////////////////// Command/Resource Queue ////////////////////

        shared_ptr<RenderCommandPipe> pm_RenderCommandQueue = nullptr;
        shared_ptr<ResourcePipe> pm_LoadedResourceQueue = nullptr;

        //////////////////// Window Stuff ////////////////////

        unordered_map<SDL_WindowID, SDL_Window*> pm_CurrentlyActiveWindows;
        vector<SDL_WindowID> pm_CloseWindowRequests;

        //////////////////// Logger ////////////////////

        shared_ptr<Logger> rendering_logger = nullptr;

        unique_ptr<unsigned char> pm_DefaultTexture = nullptr;

    public: 
        atomic<bool> pm_IsRunning{ true }; //this doesn't need to be atomic but whatevs, or even needed tbh but probs helpful for the while loop maybes
        atomic<bool> pm_IsInitialized{ false };

    //////////////////////////////////////////////
    // Public Methods
    //////////////////////////////////////////////
    public:

#ifdef PEACH_RENDERER_VULKAN
        void
            RenderLoopVK();
#endif /*PEACH_RENDERER_VULKAN*/

#ifdef PEACH_RENDERER_OPENGL
        void
            RenderLoopGL();
    private:
        [[nodiscard]] bool
            PresentFrameGL();
    public:
#endif /*PEACH_RENDERER_OPENGL*/

#ifdef PEACH_RENDERER_METAL 
        void
            RenderLoopMetal();
    private:
        [[nodiscard]] PEACH_STATUS_CODE
            InitializeMetal();

        [[nodiscard]] bool
            PresentFrameMetal();
    public:
#endif /*PEACH_RENDERER_METAL*/

#ifdef PEACH_RENDERER_OPENGL_ES
        void
            RenderLoopOpenGLES();
    private:
        [[nodiscard]] PEACH_STATUS_CODE
            InitializeOpenGLES();
    public:
#endif

#ifdef PEACH_RENDERER_WEBGL
        void
            RenderLoopWebGL();
    private:
        [[nodiscard]] PEACH_STATUS_CODE
            InitializeWebGL();
    public:
#endif /*PEACH_RENDERER_WEBGL*/

        void
            Stop()
            noexcept;

        [[nodiscard]] shared_ptr<RenderCommandPipe>
            GetDrawCommandQueue
            (
                Logger*const logger
            ); //this is supposed to be called from the main thread so cant use the rendering_logger here for thread reasons

        void 
            ResizeWindow();

        void 
            GetCurrentViewPort();

        [[nodiscard]] PEACH_FORCEINLINE bool
            IsActive()
            const noexcept
        {
            return pm_IsRunning.load(std::memory_order_acquire);
        }

        [[nodiscard]] PEACH_FORCEINLINE size_t
            GetCurrentFrameRateLimit() 
            const noexcept
        {
            return pm_CurrentFrameRateLimit;
        }

        PEACH_FORCEINLINE void
            SetNewFrameRateLimit(const size_t fp_NewFrameRateLimit)
            noexcept
        {
            pm_CurrentFrameRateLimit = fp_NewFrameRateLimit;
            RENDER_FRAME_TIME_STEP = 1.0f / (float)fp_NewFrameRateLimit;
        }

        [[nodiscard]] PEACH_FORCEINLINE bool 
            IsVSyncEnabled() 
            const noexcept
        {
            return pm_IsVSyncEnabled;
        }

        PEACH_FORCEINLINE void 
            SetVSync(const bool fp_IsEnabled)
            noexcept
        {
            pm_IsVSyncEnabled = fp_IsEnabled;
        }

    //////////////////////////////////////////////
    // Private Methods
    //////////////////////////////////////////////
    private:
        [[nodiscard]] PEACH_STATUS_CODE
            Initialize
            (
                const RendererType fp_RequiredRenderingBacked,
                SDL_Window* fp_MainWindow,
                const uint32_t fp_InitialWindowWidth,
                const uint32_t fp_InitialWindowHeight,
                const size_t fp_InitialFrameRate,
                const string& fp_LogOutputDirectory
            );

        bool
            InitializeLoadingQueue();

        bool
            InitializeDrawCommandQueue();

        [[nodiscard]] bool
            ProcessCommands();

        void
            Shutdown();
    };
}
